%%{init: { "noteAlign": "center" }}%%
sequenceDiagram
    participant browser
    participant server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa
    activate server
    server-->>browser: HTML document
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/main.css
    activate server
    server-->>browser: the css file
    deactivate server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/spa.js
    activate server
    server-->>browser: the JavaScript file
    deactivate server

    Note right of browser: The browser starts executing the JavaScript code that fetches the JSON from the server

    browser->>server: GET https://studies.cs.helsinki.fi/exampleapp/data.json
    activate server
    server-->>browser: [{ "content": "HTML is easy", "date": "2023-1-1" }, ... ]
    deactivate server

    Note right of browser: The browser executes the callback function that renders the notes

    Note left of browser: The user types in the text field
    Note left of browser: The user clicks the Save button
    Note right of browser: The form has no action or method attributes to define how and where to submit input data.

    browser->>server: POST https://studies.cs.helsinki.fi/exampleapp/new_note_spa

    Note right of server: The POST request to the new_note_spa address contains the new note as JSON data
    

    Note right of server: La cabecera Content-Type de la solicitud le dice al servidor que los datos incluidos están representados en formato JSON.
    
    server->>server: JavaScript code obtained from the server is used.


    server-->>browser: 201 Created - The server does not request a redirect

    browser->>browser: https://studies.cs.helsinki.fi/exampleapp/spa

    Note right of browser: The browser remains on the same page and does not send any more HTTP requests.